files:
  - source: /res/values/
    ignore:
      - /res/values/styles.xml
      - /res/values/dimens.xml
      - /res/values/urls.xml
      - /res/values/colors.xml
    translation: /res/values-%android_code%/%original_file_name%
