name: Android CI

on:
  push:
    branches: 
      - 'master'
      - 'dev'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Decode Keystore
      id: decode_keystore
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'android_keystore.jks'
        encodedString: ${{ secrets.KEYSTORE }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build APK and app bundle
      run: ./gradlew bundleRelease assembleRelease
      env:
        RELEASE_STORE_FILE: 'android_keystore.jks'
        RELEASE_STORE_PASSWORD : ${{ secrets.RELEASE_STORE_PASSWORD }}
        RELEASE_KEY_ALIAS : ${{ secrets.RELEASE_KEY_ALIAS }}
        RELEASE_KEY_PASSWORD : ${{ secrets.RELEASE_KEY_PASSWORD }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: AppBundle
        path: build/outputs/bundle/release/*
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: APK
        path: build/outputs/apk/release/*